### ISSUE TITLE
How to use without NPM

### ISSUE THREAD

**Issue by lesichkovm** [SuadeLabs/vue3-multiselect#3]
Can you add example how to use it without npm install @suadelabs/vue3-multiselect but from CDN?

**Comment by mattelen** [comment]
Great idea! I'll look into this in the coming days and see how it this could happen

**Comment by mattelen** [comment]
@lesichkovm I believe I have fixed this with v1.0.1 - give it a go and let me know how you get on. I'll update the documentation in the coming days

https://unpkg.com/@suadelabs/vue3-multiselect@1.0.1/dist/vue3-multiselect.js
https://unpkg.com/@suadelabs/vue3-multiselect@1.0.1/dist/vue3-multiselect.css

This should provide a variable called Vue3Multiselect
