### ISSUE TITLE
show only first five results

### ISSUE THREAD

**Issue by KLala94** [SuadeLabs/vue3-multiselect#5]
It is clear. I want to show only the first results.
And how can i style the component to make it look good.

**Comment by mattelen** [comment]
Hi @KLala94. If you want to only show the first 5 results in the dropdown, you can should be able to pass a prop of `optionsLimit`, and a number of 5 to limit what is shown. You can read in more details about this at https://vue-multiselect.js.org/#sub-props, as this version of the mulitselect works very similar to this version

If you are keen to style it, you can changes the styles by creating CSS queries and targeting different elements of the multiselect. There currently isn't a theming system or a way via JS to manipulate the colors of it. I recommend having a read of https://vue-multiselect.js.org/ too to see what options you have in terms of styling/design with props and slots.

I'll close this issue, but hope that helps.
